version: '3.2'

# Yacs primary services
# Defaults for all environments
services:
  # Application services
  core:
    build: ./core
    environment:
      - RAILS_ENV
      - SECRET_KEY_BASE
      - SECRET_TOKEN
      - WEB_CONCURRENCY
      - MAX_THREADS
    volumes:
      - ./ssl:/etc/ssl/yacs
    depends_on:
      - postgres
      - redis
    command: bin/start.sh
    expose:
      - "4100"
    extra_hosts:
      - "kafka-server:138.197.2.46"

  core-consumer:
    build: ./core
    environment:
      - RAILS_ENV
      - COURSES_TOPIC_NAME=course_change     # Customize Kafka topic name for courses here 
      - SECTIONS_TOPIC_NAME=section_change   # Customize Kafka topic name for sections here 
      - TERM_SHORTNAME
      - UNI_SHORTNAME
    depends_on:
      - postgres
      - redis
      - kafka
    command: bin/start-consumer.sh

  web:
    build: ./web
    volumes:
      - dist-web:/usr/src/app/dist-web
    depends_on:
      - core
    expose:
      - "4200"

  malg:
    build: ./malg
    depends_on:
      - kafka
      - zookeeper
      - redis
    expose:
      - "4500"
    environment:
      - UNI_SHORTNAME
      - TERM_SHORTNAME

  # Dependency services
  postgres:
    image: postgres:10.5-alpine
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
      
  redis:
    image: redis:5.0-rc-alpine
    expose:
      - "6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - core
      - users
    volumes:
      - ./ssl:/etc/ssl/yacs
      - dist-web:/usr/src/app/dist-web

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    # ports:
    #  - target: 9094
    #    published: 9094
    #    protocol: tcp
    #    mode: host
    depends_on:
      - zookeeper
    expose:
      - "9094"
      - "9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
      #KAFKA_CREATE_TOPICS: "create:1:1,update:1:1,delete:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --list"]

  # Future/abandoned services
  # admin:
  #   image: yacsrcos/yacs-admin
  #   depends_on:
  #     - core
  #   expose:
  #     - "4300"

  # notices:
  #   image: yacsrcos/yacs-notices
  #   depends_on:
  #     - postgres
  #     - redis
  #   expose:
  #     - "4900"

  # notifications:
  #   image: yacsrcos/yacs-notifications
  #   depends_on:
  #     - kafka
  #   expose: 
  #     - "3000"

  users:
    build: ./users
    environment:
      - RAILS_ENV
      - SECRET_KEY_BASE
      - SECRET_TOKEN
    volumes:
      - ./ssl:/etc/ssl/yacs
    depends_on:
      - postgres
      - redis
    command: bin/start.sh
    expose:
      - "4400"

volumes:
  dist-web:
